repos:
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
